<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.inventory.management</groupId>
		<artifactId>inventorymanagement</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>inventorymanagement-api</artifactId>
	<packaging>jar</packaging>

	<name>Inventory Management Service</name>
	<description>Inventory management service</description>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>validate</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>target/classes</outputDirectory>
							<resources>
								<resource>
									<directory>src/main/resources</directory>
									<excludes>
										<exclude>**/configprop/**</exclude>
										<exclude>**/importsSample/**</exclude>
										<exclude>**/vm-templates/**</exclude>
									</excludes>
								</resource>
							</resources>

						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<debug>true</debug>
					<verbose>true</verbose>
					<source>21</source>
					<target>21</target>
					<fork>true</fork>
					<compilerVersion>21</compilerVersion>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.32</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>